# Minifies HTML, CSS, and JS.
name: minify-page

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1

      # Commit to gh-pages
#      - uses: s0/git-publish-subdir-action@develop
#        env:
#          REPO: self
#          BRANCH: gh-pages
#          FOLDER: .
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          MESSAGE: "Build: ({sha}) {msg}"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Minify source code
          branch: gh-pages
